### ISSUE TITLE
[BUG] Add Datasources Keystore for SQL integTest on test clusters

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#2885] opened 2022-11-12 01:34 UTC
Hi,

This command is required for 2.4.0 + SQL to pass integTest:

```
curl -SLO https://github.com/opensearch-project/sql/blob/2.4/integ-test/src/test/resources/catalog/catalog.json
echo y | bin/opensearch-keystore add-file plugins.query.federation.datasources.config catalog.json
```

Temp solution:
https://github.com/peterzhuamazon/opensearch-build/blob/sql-240-test/src/test_workflow/integ_test/service_opensearch.py#L50-L67

@vamsi-amazon also confirms this change in 2.4.0 integTest runs.

Thanks.

**Comment by prudhvigodithi** [comment] 2022-12-20 02:56
Hey @peterzhuamazon @vamsi-amazon, please check the following points.

- Keystore are used to save sensitive information, I dont see anything sensitive in catalog.json, can you please tell you do we need to add it to the keystore?
- Also the added temp solution https://github.com/peterzhuamazon/opensearch-build/blob/sql-240-test/src/test_workflow/integ_test/service_opensearch.py#L50-L67, just adds `list` to the keystore which does not specifically list the added `plugins.query.federation.datasources.config`, the right test would be to use `show`.
- Adding this setting to the `service_opensearch.py` for sql would not be generic. Different repos could have different Keystore values per version.

@dblock @gaiksaya @bbarani Please add your thoughts.

Thank you

**Comment by peterzhuamazon** [comment] 2022-12-28 03:39
> * https://github.com/peterzhuamazon/opensearch-build/blob/sql-240-test/src/test_workflow/integ_test/service_opensearch.py#L50-L67

Hi @prudhvigodithi 
* I proposed this before that keystore is added through SQL plugin build.gradle.
* You can ignore the `list` command as that is just a quick check on whether the keystore is imported or not.

**Comment by vamsi-amazon** [comment] 2022-12-28 03:50
@prudhvigodithi  catalog.json can consist of accessKey, secretKey, username and password. So that's the reason we are taking it through keystore.

**Comment by zelinh** [comment] 2023-02-14 22:38
Closing this issue as this has been fixed. By adding the customized integtest script in the SQL repo (https://github.com/opensearch-project/sql/pull/1332), now the local integ test I run are passing for 2.6.0 in 2.x branch. 
Way to reproduce the passing tests:
Add a temp test manifest for 2.6.0 and run below. 
```
./test.sh integ-test manifests/2.6.0/opensearch-2.6.0-test.yml --component sql --paths opensearch=https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/2.6.0/7083/linux/x64/tar
```
```
2023-02-14 22:35:26 INFO     | sql                  | with-security        | PASS  |
2023-02-14 22:35:26 INFO     | sql                  | without-security     | PASS  |
```

**Closed by zelinh** 2023-02-14 22:38 UTC
Labels: bug, technical-debt
