### ISSUE TITLE
If bundle build failure occurs automatically restore build to a healthy state

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#486] opened 2021-09-15 15:52 UTC
When the build has been working and then starts to fail, an automated process should create notification / issue to restore the build to a functioning state.

After the failure is detected, it should:
- [x] Create a notification of the failure
- [x] Create an issue with relevant details of the failure
  - [x] Append build log information
  - [ ] Assign to the issue owner
- [ ] Revert the problematic commit

### Consideration
There are some kinds of failure that can be due to an external repository making a change where there is no code change in the current build, before auto-revert logic is added comparing the remote commit ids would likely be a requirement

**Comment by dblock** [comment] 2021-09-15 16:03
Guessing you're coming from #484?

Most of the time the problem is not going to be in this repo, but in dependent components. So I can commit something to k-NN and break the bundle build. I think the only way to avoid this is to have reliable CI everywhere, including here. In the case of #484 the issue was the custom script that should live in the upstream k-NN repo anyway, and be executed in that CI.

**Comment by gaiksaya** [comment] 2024-01-05 21:04
We recently introduced [continue-on-error](#3886) that ignores the failed components and continue to build the distribution with the one that passes. Hence build is automatically successful. The overall workflow also takes care of creating distribution build failure issues in the respective component repository. 
Automatic revert for failed component might not be a good approach here as the changes can be intentional and/or dependent on other components. I believe at this point, looking into build failure and resolving it would be the key to go forward. The component will automatically be considered in the next distribution build.

Closing this issue. Please feel free to re-open if it needs more discussion. Thanks!

**Closed by gaiksaya** 2024-01-05 21:04 UTC
Labels: enhancement
