### ISSUE TITLE
Publish nightly/rc/etc builds to docker hub

### ISSUE THREAD

**Issue by sandervandegeijn** [opensearch-project/opensearch-build#4253] opened 2023-09-14 18:23 UTC
**Is your feature request related to a problem? Please describe.**
@andrross asked me if I could test the fixes he has done for the 2.10 release. Would be happy to but since our deployment is docker based it would be helpful if the latest and greatest versions would also be on docker hub. I don't see them at docker hub.

**Describe the solution you'd like**
public nightly / release candidates / etc tags to docker hub for opensearch and dashboards.

**Describe alternatives you've considered**
Building it myself but tbh this is a bit cumbersome

**Additional context**
N/A

**Comment by bbarani** [comment] 2023-11-30 19:09
Hello @ict-one-nl we publish the nightly docker builds to Dockerhub [staging repo](https://hub.docker.com/r/opensearchstaging/opensearch/tags) to avoid noise in [production repo](https://hub.docker.com/r/opensearchproject/opensearch/tags).

**Comment by andrross** [comment] 2023-12-15 04:14
I think @ict-one-nl was able to get the build he wanted to test, he just found it odd that it was in a separate repo. As @bbarani mentioned this is by design to avoid noise. I think @ict-one-nl's suggestion is to use tags in a single repo to differentiate snapshots/RC/etc versus official releases. Feel free to close this issue if the separate repo is the preferred approach.

**Comment by ict-one-nl** [comment] 2023-12-15 08:18
Yes that's it, combined with the fact that most projects combine everything in 1 repo with tags and that the staging repo isn't easily found on the site/docs.

**Comment by jordarlu** [comment] 2024-01-24 00:06
Maybe we could add a section at the end of this [Wiki](https://github.com/opensearch-project/opensearch-build/wiki/Building-an-OpenSearch-and-OpenSearch-Dashboards-Distribution) to introduce the opensearchstaging on dockerHub ?  looping in @gaiksaya and @peterzhuamazon for more ideas to close this issue, thanks

**Comment by sandervandegeijn** [comment] 2024-01-24 08:11
Documentation would definitely help 👍

**Closed** 2024-09-19 01:34 UTC
Labels: enhancement
