### ISSUE TITLE
[BUG] Manifest auto-generation does not trigger CI

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#515] opened 2021-09-17 00:58 UTC
**Describe the bug**

Auto PRs, such as https://github.com/opensearch-project/opensearch-build/pull/514, do not trigger CI and will need a PAT token or some other workaround (currently closing and reopening the PR triggers the workflows).

**Comment by zelinh** [comment] 2022-06-20 22:09
This is still a valid issue. I see from our most recent merged PR https://github.com/opensearch-project/opensearch-build/pull/2213. Manifest CI checks were not running as well.

**Comment by gaiksaya** [comment] 2022-12-19 21:31
Looking at the most recent PR https://github.com/opensearch-project/opensearch-build/pull/2921 looks like the issue is resolved now. Closing this bug report.

**Closed by gaiksaya** 2022-12-19 21:31 UTC
Labels: bug
