### ISSUE TITLE
[BUG] Fixed build number set to 1 breaks cache busting

### ISSUE THREAD

**Issue by ginkel** [opensearch-project/opensearch-build#1769] opened 2022-02-28 09:48 UTC
**Describe the bug**

OSD delivers assets as `https://<fqdn>/1/bundles/plugin/home/home.chunk.1.js` where the first path segment is the build number. Unfortunately, this currently seems to be set to the fixed value `1` (at least for the Docker image), which causes the browser to keep caching the OSD assets even after an upgrade.

**To Reproduce**
Inspect the `package.json` inside the OSD Docker image located at: `/usr/share/opensearch-dashboards/package.json`:

```
{
  "name": "opensearch-dashboards",
  "description": "OpenSearch Dashboards is a browser based analytics and search dashboard for OpenSearch. OpenSearch Dashboards is a snap to setup and start using. OpenSearch Dashboards strives to be easy to get started with, while also being flexible and powerful, just like OpenSearch.",
  "keywords": [
    "opensearch-dashboards",
    "opensearch",
    "logstash",
    "analytics",
    "visualizations",
    "dashboards",
    "dashboarding"
  ],
  "version": "1.2.0",
  "branch": "main",
  "build": {
    "number": 1,
    "sha": "caf668e73304bac890f41c37cd6c3a41257cd289",
    "distributable": true,
    "release": true
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/opensearch-project/opensearch-dashboards.git"
  },
  "engines": {
    "node": "10.24.1"
  }
}
```

Access OSD w/ browser dev tools open and note that all assets are fetched from: `https://<fqdn>/1/...`

**Expected behavior**
The build number is set to a strictly increasing number to make sure that assets are fetched again after an OSD upgrade.

**OpenSearch Version**
1.2.3

**Dashboards Version**
1.2.0

**Plugins**
n/a

**Comment by kavilla** [comment] 2022-03-18 22:54
Linking this issue here: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1363. This is a duplicate of a cache buster being broken.

**Comment by zelinh** [comment] 2022-03-22 19:05
[Triage] Closing this issue here and please keep track in the issue here https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1363

**Comment by kavilla** [comment] 2022-03-22 19:19
@zelinh, I think this should remain open. The failure comes from something the build repo is doing and there hasn't been any public information about what the next steps will be.

**Comment by ginkel** [comment] 2022-03-22 20:06
In a private build, we have either taken the "real" CI build number or inferred the number from the Git commit hash. The latter is ugly, though, as it does not guarantee strictly increasing numbers.

**Closed** 2022-03-24 18:00 UTC
Labels: bug, opensearch-dashboards
