### ISSUE TITLE
[Bug]: OpenSearch integration test deploys stages for components absent from test manifest

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-build#3461] opened 2023-05-02 23:17 UTC
### Describe the bug

Regarding https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/opensearch/integ-test.jenkinsfile

The jenkins job compares [component list from build manifest ](https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/opensearch/integ-test.jenkinsfile#L83) against the components from the test manifest.
It deploys the jenkins parallel stage, copies everything required and then skips very late in the process that the component is not present in the test manifest. 
Also on looking at the https://build.ci.opensearch.org/blue/organizations/jenkins/integ-test/detail/integ-test/4728/pipeline it is very misleading

### To reproduce

Just take a look at https://build.ci.opensearch.org/blue/organizations/jenkins/integ-test/detail/integ-test/4728/pipeline

### Expected behavior

The comparison should be vice versa; compare components from test manifest against the components in dist or build manifest and deploy parallel stages only for the ones present in the distribution

**Comment by peterzhuamazon** [comment] 2023-05-02 23:55
Hi,

The description is not fully correct.

The check happens before the s3 download even happens:

https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/opensearch/integ-test.jenkinsfile#L121-L126

It should stop once there is a mismatch between the build and test manifest which is by design.

Thanks.

**Comment by gaiksaya** [comment] 2023-05-02 23:57
The comparison should be opposite. So that only the components in the test manifest shows the stages in jenkins pipeline. By download I mean copy https://build.ci.opensearch.org/blue/organizations/jenkins/integ-test/detail/integ-test/4728/pipeline/112 which is unnecessary. Anyway the python code takes care of the whether the components is present or not so just running for components from test manifest should be sufficient, We do not need to compare at all.

**Comment by peterzhuamazon** [comment] 2023-05-03 17:24
Hi,

Talked to @gaiksaya and we are clear now on the right implementation:
1. If user enter specific component name, then compare this name to the test manifest.
2. If use does not enter any specific component name, then just grab all the component names from the test manifest.
3. The getNames func needs to be added in the testManifest obj in lib.

Thanks.

**Comment by rishabh6788** [comment] 2023-09-18 18:25
assigning to @gaiksaya to take a look at this.

**Closed** 2024-01-18 23:09 UTC
Labels: bug
