### ISSUE TITLE
Increase the memory size for the Docker container where OSD integ test is running

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/opensearch-build#1753] opened 2022-03-14 22:38 UTC
### Is your feature request related to a problem? Please describe

We have observed more flaky test cases when OSD integ test runs in the Jenkins' Docker container. (~10+) E.g in the Github action, the failures is ~2 https://github.com/opensearch-project/opensearch-dashboards-functional-test/runs/5542235210?check_suite_focus=true

After my research, the Github action host has 7GB RAM https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners 

### Describe the solution you'd like

I am proposing to increase the Docker for running tests to have a larger memory. (8GB or even larger?)

**Comment by tianleh** [comment] 2022-03-14 22:39
Once this PR https://github.com/opensearch-project/opensearch-build/pull/1748/files is merged, the Docker image for OSD integ test will be https://hub.docker.com/r/opensearchstaging/ci-runner/tags?page=1&ordering=last_updated&name=ci-runner-rockylinux8-opensearch-dashboards-integtest-v1

**Comment by tianleh** [comment] 2022-03-14 22:40
@peterzhuamazon @kavilla @seraphjiang

**Comment by peterzhuamazon** [comment] 2022-03-15 01:29
We cannot directly change on github unless we use self-hosted runners.
On jenkins that is another story.

**Comment by tianleh** [comment] 2022-03-15 01:33
For clarify, this issue is to increase such for the Jenkins

**Comment by tianleh** [comment] 2022-03-24 23:50
Thank @kavilla for sharing the parameter to tune

`sudo sysctl -w vm.max_map_count=262144`

**Comment by bbarani** [comment] 2022-06-13 17:51
@tianleh @kavilla @peterzhuamazon Can you update the status of this issue?

**Comment by tianleh** [comment] 2022-06-15 06:56
> @tianleh @kavilla @peterzhuamazon Can you update the status of this issue?

I remember the Jenkins job has allocated larger memory for the Docker container when running integ test. Once @peterzhuamazon  confirms, we can close the issue.

**Comment by peterzhuamazon** [comment] 2022-07-12 18:19
We are not seeing flaky test caused by memory issue on virtual memory anymore.
Closing now.

Thanks.

**Closed by peterzhuamazon** 2022-07-12 18:19 UTC
Labels: enhancement
