### ISSUE TITLE
[Meta] Automate client release process by converting manual steps to automation

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#2187] opened 2022-06-10 22:41 UTC
As of now for clients such as java, js, rust, py, and more, we are still using the manual SOPs.
This causes delays between main artifacts releases and these client releases.
We want to automate the manual SOPs into the Jenkinsfile for automated releases after main artifacts online.

**Comment by dblock** [comment] 2022-06-13 16:14
I tagged this as campaign, let's standardize CD for the clients' release.

**Comment by bbarani** [comment] 2022-06-13 16:47
@gaiksaya @kartg Lets start looking in to https://github.com/opensearch-project/opensearch-build/issues/1234 for client releases.

**Comment by gaiksaya** [comment] 2022-08-01 17:20
Closing as duplicate of https://github.com/opensearch-project/opensearch-build/issues/1234

**Closed by gaiksaya** 2022-08-01 17:20 UTC
Labels: cicd, jenkins, campaign
