### ISSUE TITLE
[Bug]: Fix OS integration tests for Windows platform

### ISSUE THREAD

**Issue by rishabh6788** [opensearch-project/opensearch-build#3196] opened 2023-02-13 18:07 UTC
### Describe the bug

In the current scenario the OS integration tests have to be run manually for Windows platform as they don't run as expected. The major problem is of failure during clean-up process after the tests have run but the process fails as it is not able to delete the temp files generated during test run. 

Sample Logs: WIP

### To reproduce

On Windows 2019 machine checkout `opensearch-build` repo and run `./test.sh integ-test manifests/1.3.8/opensearch-1.3.8-test.yml --component index-management` 

### Expected behavior

The integ test should run without failing to delete the temp file generated and should display the final result of `PASS` or `FAILURE` once the test has completed.

**Comment by zelinh** [comment] 2023-07-07 23:49
I'm able to reproduce this issue on my Windows instance. 
Here are the logs:
```
Traceback (most recent call last):
    status = self.__setup_cluster_and_execute_test_config(config)
  File "C:\Users\Administrator\workspace\opensearch-build\src\test_workflow\integ_test\integ_test_suite_opensearch_dashbo
ards.py", line 104, in __setup_cluster_and_execute_test_config
    return self.execute_integtest_sh(endpoint, port, security, config)
  File "C:\Users\Administrator\scoop\apps\python39\3.9.13\lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "C:\Users\Administrator\workspace\opensearch-build\src\test_workflow\test_cluster.py", line 64, in create
    cluster.terminate()
  File "C:\Users\Administrator\workspace\opensearch-build\src\test_workflow\test_cluster.py", line 85, in terminate
    self.termination_result = self.service.terminate()
  File "C:\Users\Administrator\workspace\opensearch-build\src\test_workflow\integ_test\service.py", line 65, in terminate

    self.return_code = self.process_handler.terminate()
  File "C:\Users\Administrator\workspace\opensearch-build\src\system\process.py", line 63, in terminate
    os.remove(self.stdout.name)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users
\\ADMINI~1\\AppData\\Local\\Temp\\2\\tmpix2x74us'
```

**Comment by zelinh** [comment] 2023-07-13 23:34
According to my research, the `NamedTemporaryFile` is being accessed by `python.exe`. 
In our implementation, we are creating `self.stdout` in the `process.py` class and we are opening the file again with `open()` to read the data. 
https://github.com/opensearch-project/opensearch-build/blob/2ade8b399c1702642e4a2376b3b2130bb307a646/src/system/process.py#L60-L64

However, checking the properties of this module `NamedTemporaryFile`, I'm seeing `Whether the name can be used to open the file a second time, while the named temporary file is still open, varies across platforms (it can be so used on Unix; it cannot on Windows).` https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile
This might be the reason that python is holding these file especially on windows platform.

Let me keeping testing how we could fix this issue.

**Comment by bbarani** [comment] 2023-07-31 17:32
Closing this issue as its fixed now.

**Closed by bbarani** 2023-07-31 17:32 UTC
Labels: enhancement, integtest, windows, jenkins, technical-debt
