### ISSUE TITLE
[BUG] Transient extension mismatch in the distribution upload step

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#3097] opened 2023-01-12 20:17 UTC
It is very strange that sometimes we see certain distribution using wrong extensions, which was called in the libs repo src/jenkins/Bundle_Manifest.groovy.

```
+ cp -v C:/Users/Administrator/jenkins/workspace/distribution-build-opensearch/zip/builds/opensearch/dist/opensearch-min-2.5.0-SNAPSHOT-windows-x64.tar.gz C:/Users/Administrator/jenkins/workspace/distribution-build-opensearch/zip/builds/opensearch/dist/opensearch-min-2.5.0-SNAPSHOT-windows-x64-latest.tar.gz

cp: cannot stat 'C:/Users/Administrator/jenkins/workspace/distribution-build-opensearch/zip/builds/opensearch/dist/opensearch-min-2.5.0-SNAPSHOT-windows-x64.tar.gz': No such file or directory

script returned exit code 1
```

This does not happen often which is transient, so it is not sure where the issue is coming from. The speculation is some sort of race condition that cause the state of groovy did not update.

Similar to: https://web.archive.org/web/20181121065904/http://blog.freeside.co/2013/03/29/groovy-gotcha-for-loops-and-closure-scope/

Thanks.

**Comment by rishabh6788** [comment] 2023-01-19 22:10
Issue needs deep-dive into root cause and try to replicate.

**Comment by gaiksaya** [comment] 2023-03-24 16:59
This happened again:
```
+ cp -v C:/Users/Administrator/jenkins/workspace/distribution-build-opensearch/zip/builds/opensearch/dist/opensearch-min-2.7.0-SNAPSHOT-windows-x64.tar.gz C:/Users/Administrator/jenkins/workspace/distribution-build-opensearch/zip/builds/opensearch/dist/opensearch-min-2.7.0-SNAPSHOT-windows-x64-latest.tar.gz

cp: cannot stat 'C:/Users/Administrator/jenkins/workspace/distribution-build-opensearch/zip/builds/opensearch/dist/opensearch-min-2.7.0-SNAPSHOT-windows-x64.tar.gz': No such file or directory

script returned exit code 1
```
https://build.ci.opensearch.org/blue/organizations/jenkins/distribution-build-opensearch/detail/distribution-build-opensearch/7323/pipeline

**Comment by jordarlu** [comment] 2023-07-12 21:30
hi,, does this still happen from time to time? could it be the source file were not fully ready at the time the 'cp' was executed? maybe we can add a step to make sure the source file is ready before doing the cp ? https://stackoverflow.com/questions/38534781/check-if-a-file-exists-in-jenkins-pipeline

**Comment by prudhvigodithi** [comment] 2023-07-12 21:49
One more data point 
https://build.ci.opensearch.org/blue/organizations/jenkins/distribution-build-opensearch/detail/distribution-build-opensearch/8130/

**Comment by prudhvigodithi** [comment] 2023-11-13 19:56
Closing this as duplicate to https://github.com/opensearch-project/opensearch-build-libraries/issues/319.

**Closed by prudhvigodithi** 2023-11-13 19:56 UTC
Labels: bug, technical-debt
