### ISSUE TITLE
[Bug]: Out of date archive test distribution (for 1.1) may be causing plugin BWC test failures for Replication Plugin

### ISSUE THREAD

**Issue by ankitkala** [opensearch-project/opensearch-build#965] opened 2021-11-16 09:01 UTC
### Describe the bug

For BWC test on replication plugin, we create 1.1 clusters and upgrade those to 1.2. During the test, start replication call is failing on 1.1 cluster as it fails to resolve `INDEX_PLUGINS_REPLICATION_TRANSLOG_RETENTION_LEASE_PRUNING_ENABLED_SETTING` which is imported from `IndexSettings`: 
- https://github.com/opensearch-project/cross-cluster-replication/blob/1.1/src/main/kotlin/org/opensearch/replication/task/index/IndexReplicationTask.kt#L81
- https://github.com/opensearch-project/OpenSearch/blob/1.1/server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java#L159

```
» [2021-11-16T02:30:28.977625Z] [BUILD] Stopping node
»   ↓ last 40 non error or warning messages from /home/runner/work/cross-cluster-replication/cross-cluster-replication/build/testclusters/bwcFollower0-1/logs/opensearch.stderr.log ↓
» fatal error in thread [opensearch[bwcFollower0-1][clusterApplierService#updateTask][T#1]], exiting
»  java.lang.NoSuchFieldError: INDEX_PLUGINS_REPLICATION_TRANSLOG_RETENTION_LEASE_PRUNING_ENABLED_SETTING
»  	at org.opensearch.replication.task.index.IndexReplicationTask.<clinit>(IndexReplicationTask.kt:138)
»  	at org.opensearch.replication.task.index.IndexReplicationExecutor.createTask(IndexReplicationExecutor.kt:69)
»  	at org.opensearch.persistent.PersistentTasksNodeService$1.createTask(PersistentTasksNodeService.java:182)
»  	at org.opensearch.tasks.TaskManager.register(TaskManager.java:146)
»  	at org.opensearch.persistent.PersistentTasksNodeService.startTask(PersistentTasksNodeService.java:188)
»  	at org.opensearch.persistent.PersistentTasksNodeService.clusterChanged(PersistentTasksNodeService.java:129)
»  	at org.opensearch.cluster.service.ClusterApplierService.callClusterStateListener(ClusterApplierService.java:539)
»  	at org.opensearch.cluster.service.ClusterApplierService.callClusterStateListeners(ClusterApplierService.java:529)
»  	at org.opensearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:497)
»  	at org.opensearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:431)
»  	at org.opensearch.cluster.service.ClusterApplierService.access$000(ClusterApplierService.java:81)
»  	at org.opensearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:175)
»  	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:697)
»  	at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedOpenSearchThreadPoolExecutor.java:266)
»  	at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedOpenSearchThreadPoolExecutor.java:229)
»  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
»  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
»  	at java.base/java.lang.Thread.run(Thread.java:832)
``` 

`INDEX_PLUGINS_REPLICATION_TRANSLOG_RETENTION_LEASE_PRUNING_ENABLED_SETTING` was removed as part of 1.2(pushed to `1.x` and `main`) but should still exists in 1.1: https://github.com/opensearch-project/OpenSearch/commit/2cb71a33b8ed7ef289608809f03762768d0aeefd

I've built the OS 1.1 locally and used artifacts from maven local and didn't ran into this issue. Can you please ensure that the 1.1 artefacts are also being published correctly?

Here is the testCluster definition for BWC clusters: https://github.com/opensearch-project/cross-cluster-replication/blob/bwc_2/build.gradle#L451-L485

### To reproduce

BWC test on replication are failing on main branch right now. To circumvent this, I'm currently running it on CI in a pvt branch.
To reproduce, we can simply restart the CI job: https://github.com/opensearch-project/cross-cluster-replication/runs/4219767362?check_suite_focus=true

### Expected behavior

Replication plugin should be able to resolve `INDEX_PLUGINS_REPLICATION_TRANSLOG_RETENTION_LEASE_PRUNING_ENABLED_SETTING` on `1.1` artifacts.

**Comment by dblock** [comment] 2021-11-16 12:31
Where's the code that is downloading that 1.1 distribution? It should be taking it from https://artifacts.opensearch.org/releases/bundle/opensearch/1.1.0/opensearch-1.1.0-*.tar.gz

**Comment by dblock** [comment] 2021-11-16 16:49
> Where's the code that is downloading that 1.1 distribution? It should be taking it from https://artifacts.opensearch.org/releases/bundle/opensearch/1.1.0/opensearch-1.1.0-*.tar.gz

From a cursory code read it looks like https://github.com/opensearch-project/OpenSearch/blob/main/buildSrc/src/main/java/org/opensearch/gradle/DistributionDownloadPlugin.java#L194 doesn't know anything about the `releases/bundle` layout, which should be fixed.

**Comment by peternied** [comment] 2021-11-16 17:13
@ankitkala Please include exactly how to reproduce this issue, we can not attempt a fix if we don't know the codepath.

> To circumvent this, I'm currently running it on CI in a pvt branch.

Is this blocking the release?

**Comment by dblock** [comment] 2021-11-16 17:19
> > Where's the code that is downloading that 1.1 distribution? It should be taking it from https://artifacts.opensearch.org/releases/bundle/opensearch/1.1.0/opensearch-1.1.0-*.tar.gz
> 
> From a cursory code read it looks like https://github.com/opensearch-project/OpenSearch/blob/main/buildSrc/src/main/java/org/opensearch/gradle/DistributionDownloadPlugin.java#L194 doesn't know anything about the `releases/bundle` layout, which should be fixed.

I stay corrected.

Thats not the min release artifact. Distribution downloader will only download min artifact. See https://github.com/opensearch-project/OpenSearch/blob/1.1/buildSrc/src/main/java/org/opensearch/gradle/DistributionDownloadPlugin.java#L80.
It should be downloading: https://artifacts.opensearch.org/releases/core/opensearch/1.1.0/opensearch-min-1.1.0-linux-x64-latest.tar.gz which is valid and correct. (via @saratvemulapalli , thx)

**Comment by saratvemulapalli** [comment] 2021-11-16 17:22
@ankitkala I think the problem is downloading an older version (SNAPSHOT) artifact of 1.1.0 which is failing to deserialize the message. 
Could you try updating: https://github.com/opensearch-project/cross-cluster-replication/blob/bwc_2/build.gradle#L39 to release artifact and that should work for you.

**Comment by bbarani** [comment] 2022-01-31 22:24
@ankitkala I am closing this issue as it looks like this issue can be fixed by updating the Gradle https://github.com/opensearch-project/cross-cluster-replication/blob/bwc_2/build.gradle#L39 . Please feel free to re-open if you are still have any other issues.

**Closed by bbarani** 2022-01-31 22:24 UTC
Labels: bug
