### ISSUE TITLE
[BUG] Post script for Debian returns 255

### ISSUE THREAD

**Issue by Peronia** [opensearch-project/opensearch-build#3130] opened 2023-01-25 07:02 UTC
**Describe the bug**
I'm try to install opensearch via the apt package (first I add it to a new apt list like mentioned in the documentation):
```
root@machine:~# apt install opensearch
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
Die folgenden NEUEN Pakete werden installiert:
  opensearch
0 aktualisiert, 1 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Es müssen noch 0 B von 758 MB an Archiven heruntergeladen werden.
Nach dieser Operation werden 987 MB Plattenplatz zusätzlich benutzt.
Vormals nicht ausgewähltes Paket opensearch wird gewählt.
(Lese Datenbank ... 28468 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../opensearch_2.5.0_amd64.deb ...
Running OpenSearch Pre-Installation Script
Entpacken von opensearch (2.5.0) ...
opensearch (2.5.0) wird eingerichtet ...
Running OpenSearch Post-Installation Script
dpkg: Fehler beim Bearbeiten des Paketes opensearch (--configure):
 »installiertes opensearch-Skript des Paketes post-installation«-Unterprozess gab den Fehlerwert 255 zurück
Trigger für libc-bin (2.31-13+deb11u5) werden verarbeitet ...
Fehler traten auf beim Bearbeiten von:
 opensearch
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@machine:~# 
```

**To Reproduce**
1. add apt list for opensearch to debian
2. run `apt install opensearch`

**Expected behavior**
opensearch should be installed

**Plugins**
none

**Host/Environment (please complete the following information):**
 - OS: Debian
 - Version: 11

**Comment by peterzhuamazon** [comment] 2023-01-26 17:00
Hi @Peronia,
Sorry for inconvinience.

Could you process with these steps?

1. try to run `sudo dpkg -P opensearch`, then use `sudo apt-get opensearch`, note not using `apt` but `apt-get` as I have seen cases where apt does not install fully.
2. What is the log content of this file: `/var/log/install_demo_configuration.log`?
3. Is `/etc/opensearch` empty?

Thanks.

**Comment by Peronia** [comment] 2023-01-27 06:48
Hi @peterzhuamazon,
no problem, we are all are only humans (;

- Output from `dpkg -P opensearch`:
```
root@machine:~# dpkg -P opensearch
(Lese Datenbank ... 29831 Dateien und Verzeichnisse sind derzeit installiert.)
Entfernen von opensearch (2.5.0) ...
Running OpenSearch Pre-Removal Script
Löschen der Konfigurationsdateien von opensearch (2.5.0) ...
dpkg: Warnung: Während Entfernens von opensearch ist Verzeichnis »/var/log/opensearch« nicht leer, wird daher nicht gelöscht
dpkg: Warnung: Während Entfernens von opensearch ist Verzeichnis »/etc/opensearch« nicht leer, wird daher nicht gelöscht
Trigger für libc-bin (2.31-13+deb11u5) werden verarbeitet ...
root@machine:~# 
```
I deleted the two folders manually.
- I assume you mean `apt-get install opensearch`:
```
root@machine:~# apt-get opensearch
E: Ungültige Operation opensearch
root@machine:~# apt-get install opensearch
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
Die folgenden NEUEN Pakete werden installiert:
  opensearch
0 aktualisiert, 1 neu installiert, 0 zu entfernen und 7 nicht aktualisiert.
Es müssen noch 0 B von 758 MB an Archiven heruntergeladen werden.
Nach dieser Operation werden 987 MB Plattenplatz zusätzlich benutzt.
Vormals nicht ausgewähltes Paket opensearch wird gewählt.
(Lese Datenbank ... 28468 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../opensearch_2.5.0_amd64.deb ...
Running OpenSearch Pre-Installation Script
Entpacken von opensearch (2.5.0) ...
opensearch (2.5.0) wird eingerichtet ...
Running OpenSearch Post-Installation Script
dpkg: Fehler beim Bearbeiten des Paketes opensearch (--configure):
 »installiertes opensearch-Skript des Paketes post-installation«-Unterprozess gab den Fehlerwert 255 zurück
Trigger für libc-bin (2.31-13+deb11u5) werden verarbeitet ...
Fehler traten auf beim Bearbeiten von:
 opensearch
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@machine:~# 
```
- Content of `/var/log/opensearch/install_demo_configuration.log`:
```
**************************************************************************
** This tool will be deprecated in the next major release of OpenSearch **
** https://github.com/opensearch-project/security/issues/1755           **
**************************************************************************
OpenSearch Security Demo Installer
 ** Warning: Do not use on production or public reachable systems **
Basedir: /usr/share/opensearch
OpenSearch install type: rpm/deb on PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
OpenSearch config dir: /etc/opensearch
OpenSearch config file: /etc/opensearch/opensearch.yml
OpenSearch bin dir: /usr/share/opensearch/bin
OpenSearch plugins dir: /usr/share/opensearch/plugins
OpenSearch lib dir: /usr/share/opensearch/lib
Detected OpenSearch Version: x-content-2.5.0
Detected OpenSearch Security Version: 2.5.0.0

### Success
### Execute this script now on all your nodes and then start all nodes
### OpenSearch Security will be automatically initialized.
### If you like to change the runtime configuration 
### change the files in ../../../config/opensearch-security and execute: 
"/usr/share/opensearch/plugins/opensearch-security/tools/securityadmin.sh" -cd "/etc/opensearch/opensearch-security" -icl -key "/etc/opensearch/kirk-key.pem" -cert "/etc/opensearch/kirk.pem" -cacert "/etc/opensearch/root-ca.pem" -nhnv
### or run ./securityadmin_demo.sh
### To use the Security Plugin ConfigurationGUI
### To access your secured cluster open https://<hostname>:<HTTP port> and log in with admin/admin.
### (Ignore the SSL certificate warning because we installed self-signed demo certificates)
```
- No, `/etc/opensearch` isn't empty:
```
root@machine:~# ls -la /etc/opensearch/
insgesamt 84
drwxr-xr-x  9 root root  4096 27. Jan 07:41 .
drwxr-xr-x 82 root root  4096 27. Jan 07:41 ..
-rw-r--r--  1 root root  1704 27. Jan 07:41 esnode-key.pem
-rw-r--r--  1 root root  1720 27. Jan 07:41 esnode.pem
-rw-r--r--  1 root root  2714 27. Jan 07:41 jvm.options
drwxr-xr-x  2 root root  4096 14. Okt 12:06 jvm.options.d
-rw-r--r--  1 root root  1704 27. Jan 07:41 kirk-key.pem
-rw-r--r--  1 root root  1610 27. Jan 07:41 kirk.pem
-rw-r--r--  1 root root 14808 14. Okt 12:06 log4j2.properties
drwxr-xr-x  2 root root  4096 27. Jan 07:41 opensearch-notifications
drwxr-xr-x  2 root root  4096 27. Jan 07:41 opensearch-notifications-core
drwxr-xr-x  2 root root  4096 27. Jan 07:41 opensearch-observability
drwxr-xr-x  2 root root  4096 27. Jan 07:41 opensearch-performance-analyzer
drwxr-xr-x  2 root root  4096 27. Jan 07:41 opensearch-reports-scheduler
drwxr-xr-x  2 root root  4096 27. Jan 07:41 opensearch-security
-rw-r--r--  1 root root  4464 27. Jan 07:41 opensearch.yml
-rw-r--r--  1 root root  1444 27. Jan 07:41 root-ca.pem
root@machine:~# 
```

**Comment by peterzhuamazon** [comment] 2023-01-27 18:43
Yes @Peronia I meant to say `apt-get install`.

This is very interesting as I have never seen a case where install demo config script success, while config folder have content and still failed.

The text of the install msg seems in German, I am not sure if this has something to do with locale.
Is it possible for you to install on a English locale machine?

I will also try to switch my test machine to German and see what I can do.
Thanks.

**Comment by peterzhuamazon** [comment] 2023-01-27 19:00
Tried on debian11 English with latest upgrades:
```

admin@ip-172-31-10-24:~$ sudo apt install opensearch
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  opensearch
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 758 MB of archives.
After this operation, 987 MB of additional disk space will be used.
Get:1 https://artifacts.opensearch.org/releases/bundle/opensearch/2.x/apt stable/main amd64 opensearch amd64 2.5.0 [758 MB]
Fetched 758 MB in 24s (31.6 MB/s)
Selecting previously unselected package opensearch.
(Reading database ... 29762 files and directories currently installed.)
Preparing to unpack .../opensearch_2.5.0_amd64.deb ...
Running OpenSearch Pre-Installation Script
Unpacking opensearch (2.5.0) ...
Setting up opensearch (2.5.0) ...
Running OpenSearch Post-Installation Script
### NOT starting on installation, please execute the following statements to configure opensearch service to start automatically using systemd
 sudo systemctl daemon-reload
 sudo systemctl enable opensearch.service
### You can start opensearch service by executing
 sudo systemctl start opensearch.service
### Create opensearch demo certificates in /etc/opensearch/
 See demo certs creation log in /var/log/opensearch/install_demo_configuration.log
Processing triggers for libc-bin (2.31-13+deb11u5) ...
```

**Comment by peterzhuamazon** [comment] 2023-01-27 19:01
@Peronia can you type `locale` and let me see what is your settings?
Ex mine:
```
$ locale
LANG=C.UTF-8
LANGUAGE=
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=
```

Thanks.a

**Comment by peterzhuamazon** [comment] 2023-01-27 19:06
I switch to german locale and I am still able to install.
```
admin@ip-172-31-10-24:~$ locale
LANG=de_DE.UTF-8
LANGUAGE=
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=
admin@ip-172-31-10-24:~$ sudo apt install opensearch
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
Die folgenden NEUEN Pakete werden installiert:
  opensearch
0 aktualisiert, 1 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Es müssen 758 MB an Archiven heruntergeladen werden.
Nach dieser Operation werden 987 MB Plattenplatz zusätzlich benutzt.
Holen:1 https://artifacts.opensearch.org/releases/bundle/opensearch/2.x/apt stable/main amd64 opensearch amd64 2.5.0 [758 MB]
Es wurden 758 MB in 37 s geholt (20,7 MB/s).
Vormals nicht ausgewähltes Paket opensearch wird gewählt.
(Lese Datenbank ... 29762 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../opensearch_2.5.0_amd64.deb ...
Running OpenSearch Pre-Installation Script
Entpacken von opensearch (2.5.0) ...
opensearch (2.5.0) wird eingerichtet ...
Running OpenSearch Post-Installation Script
### NOT starting on installation, please execute the following statements to configure opensearch service to start automatically using systemd
 sudo systemctl daemon-reload
 sudo systemctl enable opensearch.service
### You can start opensearch service by executing
 sudo systemctl start opensearch.service
### Create opensearch demo certificates in /etc/opensearch/
 See demo certs creation log in /var/log/opensearch/install_demo_configuration.log
Trigger für libc-bin (2.31-13+deb11u5) werden verarbeitet ...

```

**Comment by peterzhuamazon** [comment] 2023-01-27 19:10
I think the issue lies on there are some pkgs not on your machine, therefore fail the execution of the script:
https://github.com/opensearch-project/opensearch-build/blob/main/scripts/pkg/build_templates/opensearch/deb/debian/postinst

Could you do these steps to debug:
1. purge the installation and install again, let it fail.
2. cd `/var/lib/dpkg/info`
3. Manually run `opensearch.postinst` with root permission and see what error it shows.

If we can find what exact error it is it would be very easy to go next step.

Thanks.

**Comment by Peronia** [comment] 2023-01-27 23:43
Okay, this is a strange one.
I run `bash opensearch.postinst` (do the things you mentioned before):
```
root@machine:/var/lib/dpkg/info# bash opensearch.postinst
Running OpenSearch Post-Installation Script
root@machine:/var/lib/dpkg/info#
```

Then I added echos to the script:
```
#!/bin/bash

# Copyright OpenSearch Contributors
# SPDX-License-Identifier: Apache-2.0
#
# The OpenSearch Contributors require contributions made to
# this file be licensed under the Apache-2.0 license or a
# compatible open source license.

# deb opensearch postinst script

set -e

echo "Running OpenSearch Post-Installation Script"

product_dir=/usr/share/opensearch
config_dir=/etc/opensearch
data_dir=/var/lib/opensearch
log_dir=/var/log/opensearch
pid_dir=/var/run/opensearch

# Apply Security Settings
if [ -d ${product_dir}/plugins/opensearch-security ]; then
    bash ${product_dir}/plugins/opensearch-security/tools/install_demo_configuration.sh -y -i -s > ${log_dir}/install_demo_configuration.log 2>&1
fi

echo "After first if"

# Apply PerformanceAnalyzer Settings
chmod a+rw /tmp
if ! grep -q '## OpenSearch Performance Analyzer' ${config_dir}/jvm.options; then
   # Add Performance Analyzer settings in ${config_dir}/jvm.options
   CLK_TCK=`/usr/bin/getconf CLK_TCK`
   echo >> ${config_dir}/jvm.options
   echo '## OpenSearch Performance Analyzer' >> ${config_dir}/jvm.options
   echo "-Dclk.tck=$CLK_TCK" >> ${config_dir}/jvm.options
   echo "-Djdk.attach.allowAttachSelf=true" >> ${config_dir}/jvm.options
   echo "-Djava.security.policy=file://${config_dir}/opensearch-performance-analyzer/opensearch_security.policy" >> ${config_dir}/jvm.options
   echo "--add-opens=jdk.attach/sun.tools.attach=ALL-UNNAMED" >> ${config_dir}/jvm.options
fi

echo "After second if"

# Reload systemctl daemon
if command -v systemctl > /dev/null; then
    systemctl daemon-reload
fi

echo "After third if"

# Reload other configs
sysctl -p /usr/lib/sysctl.d/opensearch.conf > /dev/null 2>&1
systemd-tmpfiles --create opensearch.conf

echo "After reload"

# Messages
echo "### NOT starting on installation, please execute the following statements to configure opensearch service to start automatically using systemd"
echo " sudo systemctl daemon-reload"
echo " sudo systemctl enable opensearch.service"
echo "### You can start opensearch service by executing"
echo " sudo systemctl start opensearch.service"

if [ -d ${product_dir}/plugins/opensearch-security ]; then
    echo "### Create opensearch demo certificates in ${config_dir}/"
    echo " See demo certs creation log in ${log_dir}/install_demo_configuration.log"
fi

echo "After fourth if"

# Set owner
chown -R opensearch.opensearch ${product_dir}
chown -R opensearch.opensearch ${config_dir}
chown -R opensearch.opensearch ${log_dir}
chown -R opensearch.opensearch ${data_dir}
chown -R opensearch.opensearch ${pid_dir}

exit 0
```

Then I have:
```
root@machine:/var/lib/dpkg/info# bash opensearch.postinst
Running OpenSearch Post-Installation Script
After first if
After second if
After third if
root@machine:/var/lib/dpkg/info#
```

So I know taht after the 3 if, nothing is executed (I don't know why). So I fired the commands amnually and all was fine. Then before I start the service, I take a look on the status:
```
root@machine:/var/lib/dpkg/info# systemctl status opensearch.service
● opensearch.service - OpenSearch
     Loaded: loaded (/usr/lib/systemd/system/opensearch.service; enabled; vendor preset: enabled)
     Active: inactive (dead)
       Docs: https://opensearch.org/
root@machine:/var/lib/dpkg/info#
```

So all good, I tried to start it and looked at the status again:
```
root@machine:/var/lib/dpkg/info# systemctl status opensearch.service
● opensearch.service - OpenSearch
     Loaded: loaded (/usr/lib/systemd/system/opensearch.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2023-01-28 00:31:14 CET; 4s ago
       Docs: https://opensearch.org/
   Main PID: 1045384 (java)
      Tasks: 71 (limit: 38375)
     Memory: 1.2G
        CPU: 29.162s
     CGroup: /system.slice/opensearch.service
             └─1045384 /usr/share/opensearch/jdk/bin/java -Xshare:auto -Dopensearch.networkaddress.cache.ttl=60 -Dopensearch.networkaddress.cac>

Jan 28 00:30:57 machine systemd[1]: Starting OpenSearch...
Jan 28 00:30:59 machine systemd-entrypoint[1045384]: WARNING: A terminally deprecated method in java.lang.System has been called
Jan 28 00:30:59 machine systemd-entrypoint[1045384]: WARNING: System::setSecurityManager has been called by org.opensearch.bootstrap.OpenSearch >
Jan 28 00:30:59 machine systemd-entrypoint[1045384]: WARNING: Please consider reporting this to the maintainers of org.opensearch.bootstrap.Open>
Jan 28 00:30:59 machine systemd-entrypoint[1045384]: WARNING: System::setSecurityManager will be removed in a future release
Jan 28 00:31:00 machine systemd-entrypoint[1045384]: WARNING: A terminally deprecated method in java.lang.System has been called
Jan 28 00:31:00 machine systemd-entrypoint[1045384]: WARNING: System::setSecurityManager has been called by org.opensearch.bootstrap.Security (f>
Jan 28 00:31:00 machine systemd-entrypoint[1045384]: WARNING: Please consider reporting this to the maintainers of org.opensearch.bootstrap.Secu>
Jan 28 00:31:00 machine systemd-entrypoint[1045384]: WARNING: System::setSecurityManager will be removed in a future release
Jan 28 00:31:14 machine systemd[1]: Started OpenSearch.
```

So all is fine...
I also tried the demo mode with ` curl -X GET https://localhost:9200 -u 'admin:admin' --insecure` and ` curl -X GET https://localhost:9200/_cat/plugins?v -u 'admin:admin' --insecure`, all works fine. I don't get it why the script doesn't run.

**Comment by peterzhuamazon** [comment] 2023-01-28 08:14
Hi @Peronia can you change this line here:
```
sysctl -p /usr/lib/sysctl.d/opensearch.conf > /dev/null 2>&1
```

to

```
sysctl -p /usr/lib/sysctl.d/opensearch.conf
```

What is the output of the script?

Also is there a way you can setup a non-root account but give it full sudo permission, and try to run with sudo instead of root user directly?

This is so strange I have never seen the case before.
Maybe if you can let me know how you setup your server, e.g. is it from a cloud provider or you manually grab a install ISO image from Debian, then I can probably reproduce on this.

Thanks.

**Comment by wynnchel** [comment] 2023-01-28 10:46
Hi @peterzhuamazon & @Peronia,

I've ran into the same issue. I'm as well as @Peronia on Debian 11. My opensearch instance is running on a lxc container managed by proxmox pve.

I've got the instance running by executing

```
chown -R opensearch:opensearch /var/lib/opensearch/                                              
chown -R opensearch:opensearch /var/log/opensearch                                               
chown -R opensearch:opensearch /etc/opensearch
```

The installer was still broken. I'm going to provide the wished outputs if the shitty DB Wifi allows me to connect home via VPN.

**Comment by Peronia** [comment] 2023-01-30 06:58
Hi @peterzhuamazon 

I've tried this (as root, after the script edit):
```
root@machine:~# bash /var/lib/dpkg/info/opensearch.postinst
Running OpenSearch Post-Installation Script
sysctl: Zugriff verweigert auf Schlüssel »vm.max_map_count«
root@machine:~#
```
Because of this, I think I don't need it to run with another user. I think here is the problem.
My echo modifications were removed before I run the script.

A strange github thing, I received an email, that Wynnchel Duncan posted here something. However, I can't see his post, so I quote my mail:

> Hi @peterzhuamazon & @Peronia,
>
>I've ran into the same issue. I'm as well as @Peronia on Debian 11. My opensearch instance is running on a lxc container managed by proxmox pve.
>
>I've got the instance running by executing
>
>chown -R opensearch:opensearch /var/lib/opensearch/                                              
>chown -R opensearch:opensearch /var/log/opensearch                                               
>chown -R opensearch:opensearch /etc/opensearch
>The installer was still broken. I'm going to provide the wished outputs if the shitty DB Wifi allows me to connect home via VPN.

My opensearch run on proxmox in a lxc container too. Maybe this is the issue?

**Comment by wynnchel** [comment] 2023-01-30 17:33
@Peronia @peterzhuamazon I've posted but deleted it afterwards. I realized that i wasn't able to reproduce all the steps I've done to get the opensearch instance up and running. Had a long an rough road weekend.

Hopefully I can provide the needed details asap. Just a theorie and based on a few minutes of tinkering last week: in my instance the user which ran the opensearch instance was called "opensearch". But this user had no permissions to write / change the folders listed above.

Above is missing the folder `/usr/share/opensearch`. I've installed it, changed the permissions, created some file and at some point it was up an running.

**Comment by peterzhuamazon** [comment] 2023-01-30 18:12
Hi @Peronia @wynnchel must related to this one then:
* https://github.com/lxc/lxd/issues/2206

**Comment by wynnchel** [comment] 2023-01-30 18:13
Will test it. Gimme a few minutes

**Comment by mnin** [comment] 2023-01-30 18:32
I tried this in a Linux container (Debian 11). The locale does not matter.

As already assumed by @peterzhuamazon, it is probably the file `/usr/lib/sysctl.d/opensearch.conf` in which the setting  `sysctl -w vm.max_map_count=262144` is in.

Even if I give the container more rights with:

```shell
lxc config set debian security.privileged true
lxc config set debian security.nesting true
```

it does not solve the problem.

If I remove line `vm.max_map_count=262144`  from the file, I can complete the installation via `apt-get install -f`.

The container, unless it is virtualized, inherits this setting from the host system.

**Comment by peterzhuamazon** [comment] 2023-02-01 18:49
Hi @Peronia @wynnchel since this seems like an issue on lxc particularly, and seems the settings can be applied on host.
Are we ok to close this issue?
Or is there any changes you guys would like to suggest?

Thanks.

**Comment by wynnchel** [comment] 2023-02-01 19:08
Feel free to close it. Thank you for your help. :)

**Comment by bbarani** [comment] 2023-02-01 23:48
Closing this issue based on the latest comment. Fee free to re-open if needed.

**Comment by dittertp** [comment] 2023-02-02 10:49
Hi,

At the moment, unfortunately, I can't see any real solution to the problem. Adjusting the systctl.d locally makes no sense from my point of view, as every update of opensearch creates/overwrites this file again. For Elasticsearch the problem was solved as follows

`
if command -v systemctl > /dev/null; then
    systemctl restart systemd-sysctl.service || true
fi
`

https://github.com/elastic/elasticsearch/blob/be7c7415627377a1b795400fb8dfcc6cbdf0e322/distribution/packages/src/common/scripts/postinst#L56


Wouldn't a similar approach be possible for opensearch? Otherwise the Debian packages would not be usable in any container environments.

**Comment by peterzhuamazon** [comment] 2023-02-02 17:23
> Hi,
> 
> At the moment, unfortunately, I can't see any real solution to the problem. Adjusting the systctl.d locally makes no sense from my point of view, as every update of opensearch creates/overwrites this file again. For Elasticsearch the problem was solved as follows
> 
> ```
> if command -v systemctl > /dev/null; then
>     systemctl restart systemd-sysctl.service || true
> fi
> ```
> 
> https://github.com/elastic/elasticsearch/blob/be7c7415627377a1b795400fb8dfcc6cbdf0e322/distribution/packages/src/common/scripts/postinst#L56
> 
> Wouldn't a similar approach be possible for opensearch? Otherwise the Debian packages would not be usable in any container environments.
> 
> Thanks!

Hi @dittertp let me take a look at it and check again.

Thanks.

**Comment by peterzhuamazon** [comment] 2023-02-02 17:51
Think it runs pretty well here.

**Comment by peterzhuamazon** [comment] 2023-02-02 17:51
Not sure if using on lxc container would actually take effect as well.

**Comment by peterzhuamazon** [comment] 2023-02-02 17:55
I doubt the solution is because of sysctl restart sysctl server, but rather `|| true`.

**Closed** 2023-02-02 21:33 UTC
Labels: bug

**Comment by dittertp** [comment] 2023-02-03 08:01
@peterzhuamazon many thanks for the quick response and for fixing the problem!

**Comment by Dataaja95** [comment] 2024-10-16 07:52
I try to install opensearch latest version Debian bookworm and I get an error, I have also tried to install version 2.15 exactly the same problem
Setting up opensearch (2.17.1) ...
Running OpenSearch Post-Installation Script
ERROR: Something went wrong during demo configuration installation. Please see the logs in /var/log/opensearch/install_demo_configuration.log
dpkg: error processing package opensearch (--configure):
 installed opensearch package post-installation script subprocess returned error exit status 1
Processing triggers for libc-bin (2.36-9+deb12u8) ...Errors were encountered while processing:  opensearch
/var/log/opensearch/install_demo_configuration.log
### OpenSearch Security Demo Installer
### ** Warning: Do not use on production or public reachable systems **
OpenSearch install type: rpm/deb on Linux 6.1.0-26-amd64 amd64
OpenSearch config dir: /etc/opensearch/
OpenSearch config file: /etc/opensearch/opensearch.yml
OpenSearch bin dir: /usr/share/opensearch/bin/
OpenSearch lib dir: /usr/share/opensearch/lib/
Detected OpenSearch Version: 2.17.1
Detected OpenSearch Security Version: 2.17.1.0
No custom admin password found. Please provide a password via the environment variable OPENSEARCH_INITIAL_ADMIN_PASSWORD.

**Comment by Dataaja95** [comment] 2024-10-16 11:04
opensearch 2.5.0 seems to work and installing Debian bookworm. Latest version 2.17.1 gives an error

**Comment by peterzhuamazon** [comment] 2024-10-16 17:55
> opensearch 2.5.0 seems to work and installing Debian bookworm. Latest version 2.17.1 gives an error

We added ADMIN Password requirement since 2.12:
```
No custom admin password found. Please provide a password via the environment variable OPENSEARCH_INITIAL_ADMIN_PASSWORD.
```

If you are starting fresh please follow the installation guide here for 2.12 and above:
https://opensearch.org/docs/latest/install-and-configure/install-opensearch/debian/#step-1-download-and-install-opensearch

Thanks.
