### ISSUE TITLE
[BUG] Docker container intermittently failing to start in CI

### ISSUE THREAD

**Issue by matthew-inamdar** [opensearch-project/opensearch-build#504] opened 2021-09-16 15:39 UTC
We're running the official OpenSearch Docker image in our CI pipeline for our automated integration tests, however, the container intermittently fails to start (around 50% of the time).

Looking at the Docker logs, it isn't clear as to why with the limited info returned (is there a way to get further logs from the container?):

```
          Name                        Command               State 
-------------------------------------------------------------------------------------------
api_opensearch-testing_1   ./opensearch-docker-entryp ...   Exit 0
                                                                                                                     
opensearch-testing_1     | Killing opensearch process 10
opensearch-testing_1     | Killing performance analyzer process 11
opensearch-testing_1     | OpenSearch exited with code 143
opensearch-testing_1     | Performance analyzer exited with code 143
```

The service entry in the docker-compose.yml file is dead simple:

```
version: "3"

services:
  # ...

  opensearch-testing:
    image: opensearchproject/opensearch:1.0.1
    environment:
      discovery.type: single-node
```

By retrying the build several times, it eventually works, but obviously, this isn't ideal. 

For reference, we're running this in GitHub Actions against their `ubuntu-18.04` environment.

Has anyone else run into this problem, or has any suggestions to try?

**Comment by peterzhuamazon** [comment] 2021-09-17 17:46
Hi @matthew-inamdar what hardware specs you are running?
We have seen rare occasion where host machine is too slow to trigger a stop due to `wait` cannot find the PID.
Can you give me your hardware specs, OS version, what exact command you are running?

Thanks.

**Comment by matthew-inamdar** [comment] 2021-09-20 10:28
Hi @peterzhuamazon I'm running the official Docker image (tag `1.0.1`) on GitHub Actions, using the `ubuntu-18.04` environment.

I've managed to get some logs from the container upon startup failure too:

```bash
$ ls /usr/share/opensearch/logs

performance-analyzer.log

$ cat /usr/share/opensearch/logs/performance-analyzer.log

OpenJDK 64-Bit Server VM warning: Option InitialBootClassLoaderMetaspaceSize was deprecated in version 15.0 and will likely be removed in a future release.
13:08:35.100 [rca-controller] ERROR org.opensearch.performanceanalyzer.rca.RcaController - Error reading file /usr/share/opensearch/data/rca_enabled.conf
java.nio.file.NoSuchFileException: /usr/share/opensearch/data/rca_enabled.conf
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218) ~[?:?]
	at java.nio.file.Files.newByteChannel(Files.java:375) ~[?:?]
	at java.nio.file.Files.newByteChannel(Files.java:426) ~[?:?]
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420) ~[?:?]
	at java.nio.file.Files.newInputStream(Files.java:160) ~[?:?]
	at java.util.Scanner.<init>(Scanner.java:718) ~[?:?]
	at org.opensearch.performanceanalyzer.rca.RcaController.lambda$readRcaEnabledFromConf$1(RcaController.java:361) [performance-analyzer-rca-1.0.1.0.jar:?]
	at org.opensearch.performanceanalyzer.core.Util.lambda$invokePrivileged$1(Util.java:78) [performance-analyzer-rca-1.0.1.0.jar:?]
	at java.security.AccessController.doPrivileged(AccessController.java:312) [?:?]
	at org.opensearch.performanceanalyzer.core.Util.invokePrivileged(Util.java:74) [performance-analyzer-rca-1.0.1.0.jar:?]
	at org.opensearch.performanceanalyzer.rca.RcaController.readRcaEnabledFromConf(RcaController.java:359) [performance-analyzer-rca-1.0.1.0.jar:?]
	at org.opensearch.performanceanalyzer.rca.RcaController.run(RcaController.java:319) [performance-analyzer-rca-1.0.1.0.jar:?]
	at org.opensearch.performanceanalyzer.PerformanceAnalyzerApp.lambda$startRcaTopLevelThread$0(PerformanceAnalyzerApp.java:195) [performance-analyzer-rca-1.0.1.0.jar:?]
	at org.opensearch.performanceanalyzer.threads.ThreadProvider.lambda$createThreadForRunnable$0(ThreadProvider.java:67) [performance-analyzer-rca-1.0.1.0.jar:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
13:08:35.464 [pa-reader] ERROR org.opensearch.performanceanalyzer.reader.ReaderMetricsProcessor - Error reading file '/usr/share/opensearch/data/batch_metrics_enabled.conf': java.nio.file.NoSuchFileException: /usr/share/opensearch/data/batch_metrics_enabled.conf
Sep 17, 2021 1:08:35 PM org.jooq.tools.JooqLogger info
INFO: 
                                      
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@  @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@        @@@@@@@@@@
@@@@@@@@@@@@@@@@  @@  @@    @@@@@@@@@@
@@@@@@@@@@  @@@@  @@  @@    @@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
@@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
@@@@@@@@@@        @@  @  @  @@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@  @@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  Thank you for using jOOQ 3.10.8
                                      
13:08:35.929 [pa-reader] ERROR org.opensearch.performanceanalyzer.reader.ReaderMetricsProcessor - Error reading file '/usr/share/opensearch/data/batch_metrics_enabled.conf': java.nio.file.NoSuchFileException: /usr/share/opensearch/data/batch_metrics_enabled.conf
13:08:37.982 [pa-reader] ERROR org.opensearch.performanceanalyzer.reader.ReaderMetricsProcessor - Error reading file '/usr/share/opensearch/data/batch_metrics_enabled.conf': java.nio.file.NoSuchFileException: /usr/share/opensearch/data/batch_metrics_enabled.conf
13:08:40.076 [rca-controller] ERROR org.opensearch.performanceanalyzer.rca.RcaController - Error reading file /usr/share/opensearch/data/rca_enabled.conf
java.nio.file.NoSuchFileException: /usr/share/opensearch/data/rca_enabled.conf
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218) ~[?:?]
	at java.nio.file.Files.newByteChannel(Files.java:375) ~[?:?]
	at java.nio.file.Files.newByteChannel(Files.java:426) ~[?:?]
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420) ~[?:?]
	at java.nio.file.Files.newInputStream(Files.java:160) ~[?:?]
	at java.util.Scanner.<init>(Scanner.java:718) ~[?:?]
	at org.opensearch.performanceanalyzer.rca.RcaController.lambda$readRcaEnabledFromConf$1(RcaController.java:361) [performance-analyzer-rca-1.0.1.0.jar:?]
	at org.opensearch.performanceanalyzer.core.Util.lambda$invokePrivileged$1(Util.java:78) [performance-analyzer-rca-1.0.1.0.jar:?]
	at java.security.AccessController.doPrivileged(AccessController.java:312) [?:?]
	at org.opensearch.performanceanalyzer.core.Util.invokePrivileged(Util.java:74) [performance-analyzer-rca-1.0.1.0.jar:?]
	at org.opensearch.performanceanalyzer.rca.RcaController.readRcaEnabledFromConf(RcaController.java:359) [performance-analyzer-rca-1.0.1.0.jar:?]
	at org.opensearch.performanceanalyzer.rca.RcaController.run(RcaController.java:319) [performance-analyzer-rca-1.0.1.0.jar:?]
	at org.opensearch.performanceanalyzer.PerformanceAnalyzerApp.lambda$startRcaTopLevelThread$0(PerformanceAnalyzerApp.java:195) [performance-analyzer-rca-1.0.1.0.jar:?]
	at org.opensearch.performanceanalyzer.threads.ThreadProvider.lambda$createThreadForRunnable$0(ThreadProvider.java:67) [performance-analyzer-rca-1.0.1.0.jar:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Sep 17, 2021 1:08:40 PM org.jooq.tools.JooqLogger info
INFO: Single batch             : No bind variables have been provided with a single statement batch execution. This may be due to accidental API misuse
Sep 17, 2021 1:08:40 PM org.jooq.tools.JooqLogger info
INFO: Single batch             : No bind variables have been provided with a single statement batch execution. This may be due to accidental API misuse
Sep 17, 2021 1:08:40 PM org.jooq.tools.JooqLogger info
INFO: Single batch             : No bind variables have been provided with a single statement batch execution. This may be due to accidental API misuse
Sep 17, 2021 1:08:40 PM org.jooq.tools.JooqLogger info
INFO: Single batch             : No bind variables have been provided with a single statement batch execution. This may be due to accidental API misuse
Sep 17, 2021 1:08:40 PM org.jooq.tools.JooqLogger info
INFO: Single batch             : No bind variables have been provided with a single statement batch execution. This may be due to accidental API misuse
Sep 17, 2021 1:08:40 PM org.jooq.tools.JooqLogger info
INFO: Single batch             : No bind variables have been provided with a single statement batch execution. This may be due to accidental API misuse
Sep 17, 2021 1:08:40 PM org.jooq.tools.JooqLogger info
INFO: Single batch             : No bind variables have been provided with a single statement batch execution. This may be due to accidental API misuse
13:08:40.603 [pa-reader] ERROR org.opensearch.performanceanalyzer.reader.ReaderMetricsProcessor - Error reading file '/usr/share/opensearch/data/batch_metrics_enabled.conf': java.nio.file.NoSuchFileException: /usr/share/opensearch/data/batch_metrics_enabled.conf
```

**Comment by peterzhuamazon** [comment] 2021-09-20 16:18
This shouldnt be an issue as PA would just treat it as a warning, it is known.
```
13:08:35.100 [rca-controller] ERROR org.opensearch.performanceanalyzer.rca.RcaController - Error reading file /usr/share/opensearch/data/rca_enabled.conf
java.nio.file.NoSuchFileException: /usr/share/opensearch/data/rca_enabled.conf
```

Would you mind send the yml you use for GitHub Actions to us?
We havent test it on GitHub Actions yet, but docker compose, helm, docker run all works well.

Thanks.

**Comment by peterzhuamazon** [comment] 2021-09-20 23:15
According to PA team this file will not created until PA started.
Dont think this cause the failure of docker since PA started.
This means OpenSearch trigger the failure.

OpenSearch needs to have these params set before you can run on docker.
https://github.com/opensearch-project/opensearch-build/tree/main/tools/standard-test#requirements

Host: `sudo sysctl -w vm.max_map_count=262144`
Dockerd: `--default-ulimit nofile=65535:65535`

I am not sure whether github actions host and dockerd have these set.
That is the most common issues to cause OpenSearch to fail.

**Comment by matthew-inamdar** [comment] 2021-09-28 10:05
@peterzhuamazon Sure, I've redacted anything confidential or unimportant:

```yaml
name: Commit

on: push

env:
  DOCKER_REGISTRY: # [REDACTED]

jobs:
  get_version:
    # [REDACTED]

  build_php_dev_image:
    # [REDACTED]

  build_php_prod_image:
    # [REDACTED]

  build_nginx_dev_image:
    # [REDACTED]

  build_nginx_prod_image:
    # [REDACTED]

  create_package:
    # [REDACTED]

  unit_tests:
    # [REDACTED]

  feature_tests:
    name: Feature Tests

    needs:
      - build_php_dev_image
      - build_nginx_dev_image

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout current commit
        uses: actions/checkout@v2.3.4

      - name: Login to GitHub Packages
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ${{ env.DOCKER_REGISTRY }} -u ${{ secrets.DOCKER_GITHUB_PACKAGES_USERNAME }} --password-stdin

      - name: Login to Docker Hub
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Pull php image
        run: docker pull ${{ env.DOCKER_REGISTRY }}/[REDACTED]/api/php:${{ needs.build_php_dev_image.outputs.image-tag }}

      - name: Tag php image
        run: docker tag ${{ env.DOCKER_REGISTRY }}/[REDACTED]/api/php:${{ needs.build_php_dev_image.outputs.image-tag }} [REDACTED]/api/php:latest

      - name: Pull nginx image
        run: docker pull ${{ env.DOCKER_REGISTRY }}/[REDACTED]/api/nginx:${{ needs.build_nginx_dev_image.outputs.image-tag }}

      - name: Tag nginx image
        run: docker tag ${{ env.DOCKER_REGISTRY }}/[REDACTED]/api/nginx:${{ needs.build_nginx_dev_image.outputs.image-tag }} [REDACTED]/api/nginx:latest

      - name: Start the containers
        run: docker-compose -f docker-compose.ci.yml up -d

      - name: Wait for MySQL to be ready
        run: |
          MYSQL_READY=false
          while [ $MYSQL_READY = false ]; do
              GREP_MATCH=$(docker-compose -f docker-compose.ci.yml logs mysql-testing | { grep "ready for connections" || true; })
              if [[ $GREP_MATCH != "" ]]; then MYSQL_READY=true; else echo "MySQL not ready. Retrying in 1 second..."; sleep 1; fi
          done

      - name: Wait for OpenSearch to be ready
        run: |
          OPENSEARCH_READY=false
          while [ $OPENSEARCH_READY = false ]; do
              HTTP_STATUS=$(docker-compose -f docker-compose.ci.yml exec -T opensearch-testing curl -k -o /dev/null -s -w "%{http_code}\n" -XGET https://admin:admin@localhost:9200 || true)
              if [[ $HTTP_STATUS = "200" ]]; then OPENSEARCH_READY=true; else echo "OpenSearch not ready. Retrying in 1 second..."; sleep 1; fi
          done
        timeout-minutes: 1

      # [REDACTED]

  code_style_tests:
    # [REDACTED]

  create_release:
    # [REDACTED]
```

**Comment by peterzhuamazon** [comment] 2022-05-12 18:24
Close this as we are not able to reproduce this issue.
Please feel free to reopen it.

Thanks.

**Closed by peterzhuamazon** 2022-05-12 18:24 UTC
Labels: bug

**Comment by matthew-inamdar** [comment] 2022-05-12 18:26
For anyone facing the same issue, we updated to the 1.1 image and haven't had the issue since.
