### ISSUE TITLE
[Workflow] Automation validating release notes

### ISSUE THREAD

**Issue by peternied** [opensearch-project/opensearch-build#698] opened 2021-10-05 22:19 UTC
We should implement a link checker, spelling checker and any other validation that can be run as part of a pull request workflow.  

https://github.com/opensearch-project/opensearch-build/pull/478

**Comment by bbarani** [comment] 2022-01-31 20:52
Closing this issue as duplicate of https://github.com/opensearch-project/opensearch-build/issues/438

**Closed by bbarani** 2022-01-31 20:52 UTC
Labels: good first issue
