### ISSUE TITLE
Trigger `integ-test` workflow after build workflow finishes 

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/opensearch-build#1114] opened 2021-11-22 18:47 UTC
### Is your feature request related to a problem? Please describe

After every run of the build workflow, `integ-test` should be triggered. The job requires parameters like opensearch_version, platform, architecture and the build id which can be pick up from the `build.yml` generated.

### Describe the solution you'd like
After distribution builds are created trigger the integration test workflow

### Acceptance Criteria:
- [ ] After the build is complete the pipeline triggers a test pipeline
- [ ] The test pipeline gets all information needed to spin up test workers
- [ ] The test pipeline triggers notifications on success/failure that are actionable
- [ ] Links to the test publisher results are consumable by receivers of the notification

**Comment by dblock** [comment] 2021-11-29 22:47
Dup of https://github.com/opensearch-project/opensearch-build/issues/818?

**Comment by ohltyler** [comment] 2022-01-05 23:22
Besides the results publishing (duplicate of #1274) I'd consider this to be a sub-issue of #818.

**Comment by dblock** [comment] 2022-01-10 18:18
I just moved the contents of this into https://github.com/opensearch-project/opensearch-build/issues/818 which seems too similar.

**Closed by dblock** 2022-01-10 18:18 UTC
Labels: enhancement
