### ISSUE TITLE
[Bug]: gradle check failing with java heap OutOfMemoryError

### ISSUE THREAD

**Issue by dreamer-89** [opensearch-project/opensearch-build#2324] opened 2022-07-11 16:23 UTC
### Describe the bug

Public jenkins gradle check job failure due to java heap OutOfMemoryError. Raised this bug to get more understanding around existing gradle check function and prevent it on different machines. The ec2 hosts were previously upgraded to c524xlarge instance. Not sure if instance needs some cleanup. 

### To reproduce

https://build.ci.opensearch.org/job/gradle-check/381

### Expected behavior

Job should not fail with 

### Host / Environment

Running on [EC2 (Amazon_ec2_cloud) - jenkinsAgentNode-Jenkins-Agent-Ubuntu2004-X64-c524xlarge-Single-Host (i-093f212ad4f5e9583)](https://build.ci.opensearch.org/computer/EC2%20%28Amazon_ec2_cloud%29%20-%20jenkinsAgentNode-Jenkins-Agent-Ubuntu2004-X64-c524xlarge-Single-Host%20%28i-093f212ad4f5e9583%29/) in /var/jenkins/workspace/gradle-check

### Relevant log output

```shell
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':example-plugins:custom-settings:compileTestJava'.
> java.lang.OutOfMemoryError: Java heap space

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':libs:opensearch-x-content:compileTestJava'.
> java.lang.OutOfMemoryError: Java heap space

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

3: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':qa:repository-multi-version:compileTestJava'.
> java.lang.OutOfMemoryError: Java heap space

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================
```
```

**Comment by peterzhuamazon** [comment] 2022-07-13 20:46
Please let us know what kind of cleanup you need.
We have:

1. Cleanup docker containers
2. Cleanup gradle cache and gradle daemons
3. Cleanup core repo

If you have any commands to clear java heap please let us know.

Thanks.

**Comment by bbarani** [comment] 2022-07-13 20:52
@dreamer-89 can you explore options to break up the gradle check tasks in to different modules? The current gradle check is very monolithic and we cannot sustain longer by increasing hardware resources.

**Comment by dreamer-89** [comment] 2022-07-15 19:18
[Another occurrence](https://github.com/opensearch-project/OpenSearch/pull/3924#issuecomment-1185831810) in https://github.com/opensearch-project/OpenSearch/pull/3924

In this case, even though the build was successful but marked failed due to heap space.

**Comment by dreamer-89** [comment] 2022-07-15 19:18
> @dreamer-89 can you explore options to break up the gradle check tasks in to different modules? The current gradle check is very monolithic and we cannot sustain it longer by continuously increasing hardware resources.



> Please let us know what kind of cleanup you need. We have:
> 
> 1. Cleanup docker containers
> 2. Cleanup gradle cache and gradle daemons
> 3. Cleanup core repo
> 
> If you have any commands to clear java heap please let us know.
> 
> Thanks.

Thanks @peterzhuamazon for providing different options. At this point, I am not sure which cleanup will help. I think we need to deep dive to understand which process is consuming the heap space.

**Comment by dreamer-89** [comment] 2022-07-15 19:20
> @dreamer-89 can you explore options to break up the gradle check tasks in to different modules? The current gradle check is very monolithic and we cannot sustain it longer by continuously increasing hardware resources.

Thanks @bbarani for the comment. I suspect the existing heap space is not due to limited hardware but instead some resource leak causing heap m/y issue. I think we need to spend brain cycles on existing failure. It could be a test but I started observing these failures recently.

**Comment by peterzhuamazon** [comment] 2022-07-15 20:21
> > @dreamer-89 can you explore options to break up the gradle check tasks in to different modules? The current gradle check is very monolithic and we cannot sustain it longer by continuously increasing hardware resources.
> 
> > Please let us know what kind of cleanup you need. We have:
> > 
> > 1. Cleanup docker containers
> > 2. Cleanup gradle cache and gradle daemons
> > 3. Cleanup core repo
> > 
> > If you have any commands to clear java heap please let us know.
> > Thanks.
> 
> Thanks @peterzhuamazon for providing different options. At this point, I am not sure which cleanup will help. I think we need to deep dive to understand which process is consuming the heap space. As this is repeating across instances, it is good to root cause and then we can try appropriate options from above.

Hi @dreamer-89 let me clarify those 3 options have ALL been applied to our script already.
Means every time when a gradle check trigger, all those 3 are already cleanup.
I am asking do you have any ways to clean up heap as I am not familiar with that.

**Comment by peterzhuamazon** [comment] 2022-07-15 20:22
Additionally I now remember I even kill all the opensearch process if any still exist.

**Comment by owaiskazi19** [comment] 2022-07-18 18:47
Can we define the recommended heap specifications to ensure container memory? Flags like `Xmx` and `Xms` mentioned [here](https://docs.cloudbees.com/docs/cloudbees-ci-kb/latest/best-practices/jvm-memory-settings-best-practice)

**Comment by bbarani** [comment] 2022-07-19 18:18
> I don't have any useful advice. But one thing that I did notice - we used to run gradle checks without these problems with a previous set of hardware/jenkins/instances, did we downgrade from that capacity-wise?

We have actually increased the hardware resources and I think we are using  [c524xlarge](https://github.com/opensearch-project/opensearch-build/pull/2298) instance  now. I assume you are seeing more errors due to the fact that we are running gradle checks more frequently now as we eliminated the need for commenting 'start gradle check' on the PR to begin the process. Having said that, I am seeing very interesting pattern where it [passes](https://build.ci.opensearch.org/job/gradle-check/) for certain amount of time and fails continuously for certain amount of time before it starts passing again.

**Comment by dblock** [comment] 2022-07-19 19:44
I hear from @peterzhuamazon that the JDK may have been changed? I would double check that G1GC is enabled.

Are these instances recycled every build?

**Comment by peterzhuamazon** [comment] 2022-07-19 19:53
> I hear from @peterzhuamazon that the JDK may have been changed? I would double check that G1GC is enabled.
> 
> Are these instances recycled every build?

I am currently writing a setup to permanently recycle all the instances.
AKA run 1 build, delete agent, provision new, run again while apply all cleanups for now.
If this runs well with higher success rate then it probably caused by some zombie process in the middle.

**Comment by peterzhuamazon** [comment] 2022-07-21 04:37
After this change gradle check generally complete between 27-40min, way quicker.
They also have less flaky runs in general.

https://build.ci.opensearch.org/job/gradle-check/853/console
https://build.ci.opensearch.org/job/gradle-check/854/console
https://build.ci.opensearch.org/job/gradle-check/855/console

Even the failure is legic failure most of the time:
https://build.ci.opensearch.org/job/gradle-check/850/console

Tho flaky test will occasionally show:
https://build.ci.opensearch.org/job/gradle-check/856/console


This seems to me that gradle test have some zomebie process / memory leak that cause the continuous flaky runs on the same runner. By restrict the runs to 1 on each brand new runner, this temporarily resolve the issue and increase the success rate.

![image](https://user-images.githubusercontent.com/65193828/180130865-587475e8-3ef6-427c-ab3d-6c3234039dff.png)

**Comment by peterzhuamazon** [comment] 2022-07-21 04:39
Remember this is not a permanent solution, we would like core team to help identify the cause within gradle check and fix the root problem.

Thanks.

**Comment by peterzhuamazon** [comment] 2022-07-21 16:10
> @peterzhuamazon I think we need to switch gradle jobs to run increasingly with `--no-daemon`. If you want to hunt that down in various build.sh scripts the projects will gladly merge that change I imagine. But also I don't see a problem with terminating agents after every large job. It gives a completely clean machine to every job. What's the cost of recycling an agent?

Hi @dblock that is already done and that is not related here. We have been using this method since fork Jenkins.

**Comment by dblock** [comment] 2022-07-21 17:11
I saw another out of memory error in https://build.ci.opensearch.org/job/gradle-check/874/

**Comment by dreamer-89** [comment] 2022-07-21 18:25
Another occurence in https://github.com/opensearch-project/OpenSearch/pull/3937

https://build.ci.opensearch.org/job/gradle-check/875/consoleFull

**Comment by dreamer-89** [comment] 2022-07-21 18:32
> Remember this is not a permanent solution, we would like core team to help identify the cause within gradle check and fix the root problem.
> 
> Thanks.

I observed heap issue locally as well. Created https://github.com/opensearch-project/OpenSearch/issues/3973 to track on core.

**Comment by peterzhuamazon** [comment] 2022-07-25 18:15
Hi @dreamer-89 let us know when you have the fix on your side, so we can implement it on Jenkins workflow.
Will close this for now, feel free to reopen the issue when needed.
Thanks.

**Closed by peterzhuamazon** 2022-07-25 18:15 UTC
Labels: bug
