### ISSUE TITLE
Check that maven repositories in each component are properly ordered and include local 

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-build#446] opened 2021-09-10 18:43 UTC
**Is your feature request related to a problem? Please describe.**

In order to build a monolith we want stable dependencies during build. Each component needs to keep `mavenLocal` in their gradle configuration, then AWS maven, then maven central, so we can drop things in maven local and get those picked up during the bundle build.

Add a CI check for this.

**Acceptance Criteria:**
When running ./build.sh manifest/x.y.z/opensearch-x.y.z.yml build fails for any component that has the maven repositories incorrectly ordered.

**Comment by peterzhuamazon** [comment] 2021-11-01 18:42
Need more investigation on how severe the problem is.

**Comment by gaiksaya** [comment] 2022-02-01 20:56
[Triage] @dblock What would be the acceptance criteria for this issue?

**Comment by dblock** [comment] 2022-02-01 22:13
> [Triage] @dblock What would be the acceptance criteria for this issue?

When running `./build.sh manifest/x.y.z/opensearch-x.y.z.yml` build fails for any component that has the maven repositories incorrectly ordered.

**Comment by gaiksaya** [comment] 2024-01-05 21:12
Closing this issue in favor of https://github.com/opensearch-project/opensearch-build/issues/637
Seems like duplicate. Thanks!

**Closed by gaiksaya** 2024-01-05 21:12 UTC
Labels: enhancement, triaged
