### ISSUE TITLE
[BUG] IntegTest failed but still show as passing due to gradle fail gracefully

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#4019] opened 2023-09-14 21:16 UTC
I was testing with maps team on OSD integTest.
And I mistakenly run OS test on a OSD image.

The OSD image only has JAVA8 which is not capable of running 2.9.0 OS integTest with this error:
```

* Try:

FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the User Manual chapter on the daemon at https://docs.gradle.org/7.6/userguide/gradle_daemon.html
Process command line: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.372.b07-4.el8.x86_64/jre/bin/java --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED -Dfile.encoding=UTF-8 -Duser.country -Duser.language=en -Duser.variant -cp /usr/share/opensearch/.gradle/wrapper/dists/gradle-7.6-bin/9l9tetv7ltxvx3i8an4pb86ye/gradle-7.6/lib/gradle-launcher-7.6.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 7.6
Please read the following process output to find out more:
-----------------------
Unrecognized option: --add-exports
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

However the result still show as success/pass here:
```

2023-09-14 19:23:11 INFO     Skipping neural-search
2023-09-14 19:23:11 INFO     Skipping notifications-core
2023-09-14 19:23:11 INFO     Skipping notifications
2023-09-14 19:23:11 INFO     Skipping opensearch-observability
2023-09-14 19:23:11 INFO     Skipping opensearch-reports
2023-09-14 19:23:11 INFO     Skipping sql
2023-09-14 19:23:11 INFO     Skipping asynchronous-search
2023-09-14 19:23:11 INFO     Skipping anomaly-detection
2023-09-14 19:23:11 INFO     Skipping alerting
2023-09-14 19:23:11 INFO     Skipping security-analytics
2023-09-14 19:23:11 INFO     Skipping index-management
2023-09-14 19:23:11 INFO     Skipping performance-analyzer
2023-09-14 19:23:11 INFO     Removing /tmp/tmpqww6o8px
2023-09-14 19:23:11 INFO     | geospatial           | with-security        | PASS  |
2023-09-14 19:23:11 INFO     | geospatial           | without-security     | PASS  |
[opensearch@ef872d4be6ca opensearch-build]$ cd test-results/
```

Checking the stdout gradle seems just fail gracefully because it could not create JVM:
```

Downloading https://services.gradle.org/distributions/gradle-7.6-bin.zip
...........10%............20%...........30%............40%............50%...........60%............70%............80%...........90%............100%

Welcome to Gradle 7.6!

Here are the highlights of this release:
 - Added support for Java 19.
 - Introduced `--rerun` flag for individual task rerun.
 - Improved dependency block for test suites to be strongly typed.
 - Added a pluggable system for Java toolchains provisioning.

For more details see https://docs.gradle.org/7.6/release-notes.html
```

This cause a false-positive to the test.

Thanks.

**Comment by rishabh6788** [comment] 2023-09-18 18:23
Needs root cause.

**Comment by rishabh6788** [comment] 2023-09-18 19:36
Seems inconsistent. Ran `geospatial` integ test on OSD image and the test failed:
```
showing failed to me
* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the User Manual chapter on the daemon at https://docs.gradle.org/7.6/userguide/gradle_daemon.html
Process command line: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.372.b07-4.el8.x86_64/jre/bin/java --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED -Dfile.encoding=UTF-8 -Duser.country -Duser.language=en -Duser.variant -cp /usr/share/opensearch/.gradle/wrapper/dists/gradle-7.6-bin/9l9tetv7ltxvx3i8an4pb86ye/gradle-7.6/lib/gradle-launcher-7.6.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 7.6
Please read the following process output to find out more:
-----------------------
Unrecognized option: --add-exports
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

2023-09-18 19:30:13 INFO     Sending SIGKILL to PID 1092
2023-09-18 19:30:13 INFO     Process killed with exit code None
2023-09-18 19:30:13 INFO     Recording local cluster logs for geospatial with test configuration as without-security at /usr/share/opensearch/opensearch-build/test-results/78cc21250f10477983c2c7b05c87717b/integ-test/geospatial/without-security/local-cluster-logs
2023-09-18 19:30:13 INFO     Cleanup /tmp/tmp13u_twkm/1/local-test-cluster/opensearch-2.9.0 content after the test
2023-09-18 19:30:13 INFO     Recording component test results for geospatial at /usr/share/opensearch/opensearch-build/test-results/78cc21250f10477983c2c7b05c87717b/integ-test/geospatial/with-security
2023-09-18 19:30:13 INFO     Walking tree from /usr/share/opensearch/opensearch-build/test-results/78cc21250f10477983c2c7b05c87717b/integ-test/geospatial/with-security
2023-09-18 19:30:13 INFO     Recording component test results for geospatial at /usr/share/opensearch/opensearch-build/test-results/78cc21250f10477983c2c7b05c87717b/integ-test/geospatial/without-security
2023-09-18 19:30:13 INFO     Walking tree from /usr/share/opensearch/opensearch-build/test-results/78cc21250f10477983c2c7b05c87717b/integ-test/geospatial/without-security
2023-09-18 19:30:13 INFO     Skipping security
2023-09-18 19:30:13 INFO     Skipping cross-cluster-replication
2023-09-18 19:30:13 INFO     Skipping ml-commons
2023-09-18 19:30:13 INFO     Skipping neural-search
2023-09-18 19:30:13 INFO     Skipping notifications-core
2023-09-18 19:30:13 INFO     Skipping notifications
2023-09-18 19:30:13 INFO     Skipping opensearch-observability
2023-09-18 19:30:13 INFO     Skipping opensearch-reports
2023-09-18 19:30:13 INFO     Skipping sql
2023-09-18 19:30:13 INFO     Skipping asynchronous-search
2023-09-18 19:30:13 INFO     Skipping anomaly-detection
2023-09-18 19:30:13 INFO     Skipping alerting
2023-09-18 19:30:13 INFO     Skipping security-analytics
2023-09-18 19:30:13 INFO     Skipping index-management
2023-09-18 19:30:13 INFO     Skipping performance-analyzer
2023-09-18 19:30:13 INFO     Removing /tmp/tmp13u_twkm
2023-09-18 19:30:13 ERROR    | geospatial           | with-security        | FAIL  |
2023-09-18 19:30:13 ERROR    | geospatial           | without-security     | FAIL  |
```

`stderr` file from test-results dir:
```
FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the User Manual chapter on the daemon at https://docs.gradle.org/7.6/userguide/gradle_daemon.html
Process command line: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.372.b07-4.el8.x86_64/jre/bin/java --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED -Dfile.encodi
ng=UTF-8 -Duser.country -Duser.language=en -Duser.variant -cp /usr/share/opensearch/.gradle/wrapper/dists/gradle-7.6-bin/9l9tetv7ltxvx3i8an4pb86ye/gradle-7.6/lib/gradle-launcher-7.6.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 7.6
Please read the following process output to find out more:
-----------------------
Unrecognized option: --add-exports
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
```

**Comment by rishabh6788** [comment] 2023-09-18 19:46
seems @peterzhuamazon added additional `tee` command after the integ-test command in the python script for debugging that caused the exit code to be 0. 
Closing this issue.

**Closed by rishabh6788** 2023-09-18 19:46 UTC
Labels: bug, integtest, cicd
