### ISSUE TITLE
opensearch-js npm publish 2.0.0

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/opensearch-build#2145] opened 2022-05-25 18:44 UTC
### Is your feature request related to a problem? Please describe

@opensearch-project/opensearch 2.0.0

### Describe the solution you'd like

npm publish for opensearch-js

**Comment by bbarani** [comment] 2022-05-26 16:27
@ananzh It looks like @VachaShah is already working in publishing clients for 2.0 release. This issue seems to be a duplicate of https://github.com/opensearch-project/opensearch-build/issues/2140

**Comment by ananzh** [comment] 2022-05-26 20:33
@bbarani It is part of the clients release. opensearch-js is special because it needs an extra npm publish besides the release. If we don't need another issue to track on this, I could close it.

**Comment by bbarani** [comment] 2022-06-01 18:16
Closing this issue as we have published the opensearch-js 2.0 [version](https://www.npmjs.com/package/@opensearch-project/opensearch/v/2.0.0) .

**Closed by bbarani** 2022-06-01 18:16 UTC
Labels: enhancement
