### ISSUE TITLE
Enable different visualization color for staging if unstable

### ISSUE THREAD

**Issue by zelinh** [opensearch-project/opensearch-build#4018] opened 2023-09-14 20:34 UTC
### Is your feature request related to a problem? Please describe

Currently we enable a new `-continue-on-error` into our distribution build; in this way, the build jenkins job won't stop if it fails on some plugins, but gives `unstable` at the end of the job results. 

However, looking into each stages inside the build jenkins job, all of the stages are green.
e.g.
<img width="2378" alt="Screenshot 2023-09-14 at 1 23 38 PM" src="https://github.com/opensearch-project/opensearch-build/assets/87548827/bd8e4f3f-34b1-4112-bd80-4fcd3cb03ada">
It's hard for us to locate which stage actually fails unless we search through the entire console log which is extremely time-consuming.

### Describe the solution you'd like

Jenkins should have the option to change the stage status to `unstable` so it will display different color as yellow in Blue Ocean as well. 
https://www.jenkins.io/blog/2019/07/05/jenkins-pipeline-stage-result-visualization-improvements/

I'm suggesting if we are running distribution build job with `continue-on-error`, we should not only update the final job status to unstable but also the specific stage that has error. This will be more informative and easier for maintenance.

### Acceptance Criteria:
1. If a non-mandatory component failure happens at a stage level, that stage should be marked as `unstable`. 
2. The overall job status should be `unstable`.

**Comment by ScreamingPigeon** [comment] 2023-10-13 17:58
@gaiksaya I would like to work on this issue. The blog that explains the issue is fairly straightforward - however, I'm not sure which subdirectories/files need those changes. Some information on that topic would be appreciated

**Comment by zelinh** [comment] 2023-10-13 18:58
> @gaiksaya I would like to work on this issue. The blog that explains the issue is fairly straightforward - however, I'm not sure which subdirectories/files need those changes. Some information on that topic would be appreciated

I think you could look into these two files. These are the `distribution-build` jenkinsfile for OpenSearch & OpenSearch Dashboards this issue addresses on. 
https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/opensearch/distribution-build.jenkinsfile
https://github.com/opensearch-project/opensearch-build/blob/main/jenkins/opensearch-dashboards/distribution-build.jenkinsfile

**Comment by ScreamingPigeon** [comment] 2023-10-16 17:24
Thank you. I'll get started

**Comment by gaiksaya** [comment] 2023-10-16 17:56
See https://github.com/opensearch-project/opensearch-ci as the that is the source of the CI system (jenkins). If you do have access to the resources to deploy the CI system, you can use this docker image mentioned here https://github.com/opensearch-project/opensearch-ci/blob/main/resources/docker-compose.yml#L4 to see what all plugins and its versions are currently installed on the system.

Assigning this issue to you @ScreamingPigeon

**Comment by gaiksaya** [comment] 2023-11-17 18:29
Hi @ScreamingPigeon 

Since there is no progress on this issue for a month, I'll be taking over. Have an alternate approach that I tried and it worked. 
Thanks!

**Closed** 2023-12-13 18:34 UTC
Labels: enhancement, good first issue, cicd, jenkins

**Comment by gaiksaya** [comment] 2023-12-15 03:57
We can now see the each stage that has failed plugins marked as unstable https://build.ci.opensearch.org/blue/organizations/jenkins/distribution-build-opensearch/detail/distribution-build-opensearch/9028/pipeline/

See the above PRs links for more details on the execution.
Thanks!
